language: python:2.7

services:
  - docker

script:
  - sh ./docker-build.sh
  - sh ./build-containers.sh

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: 
    - build/**/*.rpm
  skip_cleanup: true
  on:
    tags: true
